deepspeed --num_gpus 4 --num_nodes 1 cli/train.py \
    --output_dir /workspace/.cache/models \
    --init_ckpt /pretrained/llama-2-7b-hf-4shard \
    --data_path /datasets/prompt.jsonl \
    --max_seq_len 2 \
    --train_steps 1000 \
    --eval_steps 10 \
    --save_steps 1000 \
    --log_steps 10 \
    --pipe_parallel_size 1 \
    --model_parallel_size 4 \
    --use_flash_attn true \
    --use_fused_ops true \
    --deepspeed_config ./configs/llama.json